<a href="https://colab.research.google.com/github/Akshayakrishna262/mlapplications/blob/main/FeatureEng.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd


In [ ]:
filename='/content/pima-indians-diabetes.data(ad).csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']


In [ ]:
dataframe=read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]

In [ ]:
test=SelectKBest(score_func=chi2,k=4)
fit=test.fit(X,Y)


In [ ]:
print(names)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']


In [ ]:
set_printoptions(precision=3)
print(fit.scores_)
features=fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [ ]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
model = LogisticRegression(max_iter=400)
rfe = RFE(estimator=model,n_features_to_select=3)
fit = rfe.fit(X, Y)

In [ ]:
fit.n_features_

3

In [ ]:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [ ]:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [ ]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

In [ ]:
filename='/content/pima-indians-diabetes.data.csv'
names = ['preg','plas','pres','skin','test','mass','pedi','age','class']
print(names)
dataframe=read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]
model=DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']


FileNotFoundError: [Errno 2] No such file or directory: '/content/pima-indians-diabetes.data.csv'