<a href="https://colab.research.google.com/github/Akshayakrishna262/mlapplications/blob/main/FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Feature Extraction with Univariate Statistical Tests (Chi-squared for classification)
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
# load data
filename = '/content/pima-indians-diabetes.data(ad).csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
print(names)
#df = pd.read_csv(r"/content/pima-indians-diabetes.data(ad).csv")
#print(df)
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]
# feature extraction
test = SelectKBest (score_func=chi2, k=4)
fit=test.fit(X, Y)
# summarize scores
print(fit.scores_)
features = fit.transform(X)
# summarize selected features
print(features[0:5,:])
set_printoptions (precision=3)
print(fit.scores_)
features = fit.transform(X)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]
[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]]
[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [ ]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pandas as pd
# load data
filename = '/content/pima-indians-diabetes.data(ad).csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
print(names)
#df = pd.read_csv(r"/content/pima-indians-diabetes.data(ad).csv")
#print(df)
dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

model = LogisticRegression(max_iter=400)

rfe = RFE(estimator=model, n_features_to_select=3)

fit = rfe.fit(X, Y)


['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']


In [ ]:
fit.n_features_

3

In [ ]:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [ ]:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])